### ISSUE TITLE
Error writing to Slides

### ISSUE THREAD

**Issue by thewinger** [websiddu/sync-to-slides#1]
Is there a max width&height for sketch artboards?

Is giving me error writing to slides all the time

![sketch-slides](https://cloud.githubusercontent.com/assets/121455/26821554/15496a7a-4aa7-11e7-8c97-8bb40b606776.gif)

The artboard is 9416x6269

**Comment by websiddu** [comment]
That is super big and google slides may not handle that big images I guess.

**Comment by thewinger** [comment]
I suppose it was that.

Thank you for your quick reply!
