### ISSUE TITLE
Editable Texts

### ISSUE THREAD

**Issue by marciogranzotto** [websiddu/sync-to-slides#10]
I need to edit the texts that are exported on Google Slides, but apparently they are not editable. The plugin just creates a empty text box on top of the actual text.
There's any way to do that?

**Comment by websiddu** [comment]
Its kind of out of scope at this point. And its make it hard to sync back and fourth. Its will be super hard to sync the changes back to sketch documents. 

And that needs a lot of work :) Closing for now.
