### ISSUE TITLE
Empty object layers imported to slides

### ISSUE THREAD

**Issue by okayjeffrey** [websiddu/sync-to-slides#11]
When selecting "Layers" in preferences. A flat graphic is uploaded as the background of the slide (which shows the whole graphic) but then empty objects representing where those layers would be are there. _Happens on all objects (text, shapes, etc)_

![blank_objects](https://user-images.githubusercontent.com/99021/27664535-dfa3328e-5c1c-11e7-87b1-68e401b555f2.png)

**Comment by websiddu** [comment]
That will enable you to comment and get feedback on a particular piece of element :) That is the whole point of this plugin.

**Comment by okayjeffrey** [comment]
Oh... that is interesting. Are slides that complex that the standard
commenting not efficient?

Also am I missing the purpose of this plugin? If this syncs sketch files to
slides, importing the actual objects/elements (that could also be commented
on) would allow the use of animation with the slides, which sometimes is
important with presentations.

I am stoked on the work you have done here, this just appeared as a bug and
now is fairly limiting for actual presentation creation (basic decks it's
perfect).

Thank you for creating this and hopefully my feedback helps!

**Comment by websiddu** [comment]
As I mentioned in other similar issue. Its possible to export individual slides element (just like sketch to framer or flinto). But it generally takes longer time to export all individual images and slides may not handle all those images on a single slide. 

And more over once you start moving around your layers in the slides deck, it will be hard to sync them back to sketch. There are some other technical issues and disadvantages of doing that. 

So for now give the time I have to work on this. Its not a good idea for me to start on this :) Hope you can understand.
