### ISSUE TITLE
After signing into Google, Sync to Slides panel doesn't update 

### ISSUE THREAD

**Issue by annareedsmalley** [websiddu/sync-to-slides#5]
Hi! REALLY excited to use this... but no matter what I do, after I open up Sync to Slides in Sketch and sign in to Google, the Sync to Slides panel never updates to give me a place to paste my slide deck url. I've tried signing into different google accounts... restarting sketch... everything. But all I can get Sync to Slides to do is to show me the screen shown here, asking me to sign into Google. Help? Thanks!! 
![image](https://user-images.githubusercontent.com/13755902/27256168-3dba9baa-5362-11e7-9654-16a531c8f843.png)

**Comment by annareedsmalley** [comment]
Also, sometimes when I click on "Sign in with Google" in the panel above, Sketch crashes. I'm using the latest version of Sketch. Thank you!!

**Comment by websiddu** [comment]
I'm not sure why you are facing those issues. One thing that I would really suggest is re-install sketch.

**Comment by annareedsmalley** [comment]
Thanks Siddhartha- I will try that!
