### ISSUE TITLE
You shall not pass error.  Can't connect to Google slides

### ISSUE THREAD

**Issue by freshlesh3** [websiddu/sync-to-slides#6]
Can't connect to Google slides.  I keep getting a you shall not pass error.

**Comment by websiddu** [comment]
Please check if you have write permissions for your slides.

**Comment by freshlesh3** [comment]
I changed the share permissions that allow editting, is that what you mean by write permissions?

--

**Comment by freshlesh3** [comment]
This is what I see in the plugin.

--

**Comment by freshlesh3** [comment]
You never addressed the issue and closed the topic?

**Comment by websiddu** [comment]
1. Are you using @gmail.com account or your company email id? If its your company id you have to whitelist the app sync-to-slides app 
2. If you don't have write permission slides. Create a new slides document with the signed in id and make sure you have write access. 
Final option, 
Re-install sketch that will help to clear the old keys and generate new keys.
